/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Cutlist: typeof import('./src/components/Cutlist.vue')['default']
    FlatCrate: typeof import('./src/components/FlatCrate.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    JobPrompt: typeof import('./src/components/JobPrompt.vue')['default']
    PanelSetDialog: typeof import('./src/components/PanelSetDialog.vue')['default']
  }
}
