/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddMaterialSetItem: typeof import('./src/components/AddMaterialSetItem.vue')['default']
    AddPanelSet: typeof import('./src/components/AddPanelSet.vue')['default']
    FlatCrate: typeof import('./src/components/FlatCrate.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}
